WDP200901-4
PatrykBulaKodilla/wdp-2009-01 pull request #3
Opened 2020-09-02 13:17 UTC by ThePojers

Current state: Static buttons on element(Product box)

Future state: Hovering the cursor over the product box displays the "Quick view" and "Add to cart" buttons. The 'price' background color also changes.

2020-09-02 19:48 UTC, PatrykBulaKodilla requested changes

2020-09-02 19:48 UTC, PatrykBulaKodilla commented on src/components/common/ProductBox/ProductBox.module.scss
> +    .price :first-child{
Czy ta spacja jest konieczna?

2020-09-02 19:48 UTC, PatrykBulaKodilla commented on src/components/common/ProductBox/ProductBox.module.scss
> +  .price :first-child{
Jak niżej

2020-09-02 20:34 UTC, ThePojers commented on src/components/common/ProductBox/ProductBox.module.scss
> +    .price :first-child{
Wydaję się być konieczna bo po usunięciu spacji hover nie działa

2020-09-04 20:29 UTC, PatrykBulaKodilla approved these changes

2020-09-04 20:29 UTC, merged